export const Config = {
  // Canvas
  CANVAS_WIDTH: 640,
  CANVAS_HEIGHT: 480,

  // Player
  PLAYER_SPEED: 3.5,
  PLAYER_ROT_SPEED: 2.2,
  MOUSE_SENSITIVITY: 0.0018,
  PLAYER_COLLISION_RADIUS: 0.28,
  FOV_PLANE: 0.66,
  PLAYER_START_X: 2.5,
  PLAYER_START_Y: 2.5,
  PLAYER_START_DIR_X: 1.0,
  PLAYER_START_DIR_Y: 0.0,
  MAX_SIGNAL: 100,

  // Raycasting
  NUM_RAYS: 640,
  TEX_SIZE: 64,
  MAX_DEPTH: 24,
  WALL_SHADE_SIDE: 0.62,

  // Anomaly – Wanderer
  WANDERER_ORBIT_SPEED: 0.45,
  WANDERER_ORBIT_RADIUS: 2.2,
  WANDERER_ACTIVATE_RANGE: 12,

  // Anomaly – Observer
  OBSERVER_RANGE: 9,
  OBSERVER_ROT_SPEED: 2.8,

  // Anomaly – Echo
  ECHO_SAMPLE_INTERVAL: 200,
  ECHO_TRAIL_LENGTH: 30,

  // Anomaly – Resonator
  RESONATOR_PULSE_HZ: 0.6,
  RESONATOR_RANGE: 7,
  RESONATOR_WARP_AMT: 14,

  // Scan
  SCAN_RANGE: 6,
  SCAN_HOLD_DURATION: 2200,
  SCAN_FOV_HALF: 0.22,

  // Signal / anchor
  LOW_SIGNAL_DRAIN_RATE: 18,
  DISPLACEMENT_SIGNAL_RESTORE: 50,
  DISPLACEMENT_DURATION: 1600,

  // Doors
  DOOR_OPEN_SPEED: 1.4,
  DOOR_TRIGGER_RANGE: 1.6,
  DOOR_OPEN_TIME: 3.0,

  // Audio
  BASE_DRONE_HZ: 82,
  DRONE_PROXIMITY_SCALE: 45,

  // Timing
  DELTA_CAP: 0.1,

  // Map
  MAP_WIDTH: 24,
  MAP_HEIGHT: 24,

  // Cell types
  CELL_EMPTY: 0,
  CELL_CONCRETE: 1,
  CELL_TEAL: 2,
  CELL_BIO: 3,
  CELL_SYMBOL: 4,
  CELL_DOOR: 9,

  // Door states
  DOOR_CLOSED: 0,
  DOOR_OPENING: 1,
  DOOR_OPEN: 2,
  DOOR_CLOSING: 3,

  // Game states
  STATE_LOADING: 'LOADING',
  STATE_MENU: 'MENU',
  STATE_PLAYING: 'PLAYING',
  STATE_LOG_OPEN: 'LOG_OPEN',
  STATE_DISPLACED: 'DISPLACED',
  STATE_WIN: 'WIN',

  // Minimap
  MINIMAP_SCALE: 4,
  MINIMAP_X: 10,
  MINIMAP_Y: 10,
};
